before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
language: android
jdk:
- oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - build-tools-25.0.2
  - android-25
  - extra-android-m2repository
  - extra-android-support
  - doc-25
branches:
  only:
  - master
script: "./travis-build.sh"
notifications:
  slack:
    rooms:
      secure: O20dbm4jv8o2dnWzxT/5hYwDm2tFMn4j/eVMAeHkzb/68yOiAmi0tVmfU3KkcD30swNHEi0BgNFoZi40YQ9Ofk7yVWvcoPEjvYUQt7lBhYScZOuvGgYskqywitqc2CBK3klIG2PEcZuYZlCyZIySUdfe3TpWO3/8fWsWN6lPg+2PPTyLnKW2ch37Uml3d9EFgJ6p8zRRRON8602+LsnCpnU94VJsC2fay6UhLf57CDRPhLCWCgAPhAZSRVaPqal8DPm/C/u4xJMIMxz9IwF1tA1tdjPClTDLPeifGstLcLfopb+r2K66OyHXdJoGUHJeneWEF3wDAxDXzh+hJoEww+zcKXd6wL9bmNmSqAU7jIdfWnm7rQiH6T8wO6/0sGrDHUuPQuZu3C0UqMFCCUNYTZjKG1XSx+7bx/cOeH8brSw7tjFZkUJmUwqYIlOCZlH8kdR22h9hziIuJf7RTBaNBK6+Zu1Hdnqb+USaES7NfrDBMSPp27C3IpjIGIISltx9lO5ld4kg9Dm5o1Kh1l8MHJEYlO2k4ZWdXS4dRXiGC4Jd2+uWHwZ3mE6+XpNkH/WOYBjD9UCZJSAlMzqjl634NH8Sk50p8/lYALcRgRvCJvdoeU6xz8zXWPHOKJqSJerJku9iJ5W06abZXlUiVuioO/xsTVFB3zDwj6J/bzUWPpk=
    on_pull_requests: false
    on_failure: always
    on_start: never
    on_success: change
env:
  matrix:
    secure: nnuCxQ/T2wIEg+IcFQbQLip5dZMpJe5ATA1dwV9t1KjmhIkhnrjABIltiLm0o2o88Rt46dt9ZSmSDTz/GaR+Kuni8gmu/OM0Rsy3aOXF+shfvZJNfecaM8FZI0pP6hV/Nx9PsY7/NOZunpYdh4DCIS4rN1SIEM+cagJKtQfta75BXu0XQHgXYyaz3NN2Ao/4c0KxCP2cwdwvSWqamQJuUUZ+Zc5xG9w8N3/EHgBa88Ai+xs2ZpFWY9XoNzHql6/AqDNLTbPgUqMz6p37j9eBtn1x/O87ips7jSuF1LDbp5zmRUbgAxdOX4EMI1efwU69+lACeQcZ5n/cyf3Nr4L2F7rNCyiaROfALt3fYzgHWBFOTHlvlFzyovmtrEPUm9bScR6xG1McnqNmwZY3laCPr+YlkMFQT9df3fGsk/XWTjDdHnxtudNjD3kw1IVCwW73ULiqpz8KGN5+uf9TPBD6916dmsha7+ZajzNywLfZqyeSuJ60/vyqoSnEYWVRm+x4l7Vo7aNO1wsLiiUmoDLtNDHciZ9ssNTexoCOdIpiXWYNv4Xn9l8L/0dqQHOCdafnhKbhHE+MDMyRR/PNDPmr5oFSeb/RJEwsKl0xkaTPNqT5IQenGRZgUmjvBZjoUeQE+9C39YuGaAO6nTyMBSCupwmorNW3hQJLovLKEirwf4Q=
