cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.2
  - android-23
  - extra-android-m2repository
  - extra-android-support
  - doc-23
branches:
  only:
  - master
script: "./travis-build.sh"
notifications:
  slack:
    rooms:
      secure: O20dbm4jv8o2dnWzxT/5hYwDm2tFMn4j/eVMAeHkzb/68yOiAmi0tVmfU3KkcD30swNHEi0BgNFoZi40YQ9Ofk7yVWvcoPEjvYUQt7lBhYScZOuvGgYskqywitqc2CBK3klIG2PEcZuYZlCyZIySUdfe3TpWO3/8fWsWN6lPg+2PPTyLnKW2ch37Uml3d9EFgJ6p8zRRRON8602+LsnCpnU94VJsC2fay6UhLf57CDRPhLCWCgAPhAZSRVaPqal8DPm/C/u4xJMIMxz9IwF1tA1tdjPClTDLPeifGstLcLfopb+r2K66OyHXdJoGUHJeneWEF3wDAxDXzh+hJoEww+zcKXd6wL9bmNmSqAU7jIdfWnm7rQiH6T8wO6/0sGrDHUuPQuZu3C0UqMFCCUNYTZjKG1XSx+7bx/cOeH8brSw7tjFZkUJmUwqYIlOCZlH8kdR22h9hziIuJf7RTBaNBK6+Zu1Hdnqb+USaES7NfrDBMSPp27C3IpjIGIISltx9lO5ld4kg9Dm5o1Kh1l8MHJEYlO2k4ZWdXS4dRXiGC4Jd2+uWHwZ3mE6+XpNkH/WOYBjD9UCZJSAlMzqjl634NH8Sk50p8/lYALcRgRvCJvdoeU6xz8zXWPHOKJqSJerJku9iJ5W06abZXlUiVuioO/xsTVFB3zDwj6J/bzUWPpk=
    on_pull_requests: false
    on_failure: always
    on_start: never
    on_success: change